language: php

php:
  - 5.4

env:
  global:
    - PLUGIN_NAME=PermissionsComponent
    - REQUIRE="cakephp/debug_kit:2.2.* cakedc/search:dev-develop"
    - DB=mysql CAKE_VERSION=2.4

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false