language: php
php:
- 5.4
env:
  global:
  - PLUGIN_NAME=PermissionsComponent
  - REQUIRE="cakephp/debug_kit:2.2.* cakedc/search:dev-develop"
  - DB=mysql CAKE_VERSION=2.4
  - secure: YILbHe3BiRVN4r91UTeIN3fiJLmnlFHVB7wqi+ocyhMEQPE/655zrbQvUCRxNpRST2UkW+TcMeePyGoKpc9bMS5ZVhJeT7yy7GM1vx1T1yLcc+i60ObnYU9V6W5K0f0sDUYdStZbuyHRMKTYfR+uqo9JEWC7o4vWKjw95vb8/FU=
  - secure: ob6T8bFRxdMrw/lVzpS6rIx196APm6oy38Sy+0jBh338e47nYiLfZ9jS0fRySEPYjR9rxZ82EQPLktKNQi4el2sYdodqSNbNfF0gTZjBBURc+F1JyWfSyepY0FxeakTwyuqnuwIJ0jnm61iwnHY3cn0coifOkUJibF32vgZsSls=
before_script:
- git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
- ../travis/before_script.sh
script:
- ../travis/script.sh
after_success:
- wget http://phpdoc.org/phpDocumentor.phar
- php phpDocumentor.phar --directory="Controller"
- sudo apt-get install ncftp
- ncftpput -R -m -u $FTP_USER -p $FTP_PASSWORD host3.label305.com /cakephp-permissions-component/$TRAVIS_BRANCH output/*
- ../travis/after_success.sh
notifications:
  email: false
